config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("account.urls", namespace="account")),
    path("main/", include("main.urls", namespace="main")),
    path("structure/", include("structure.urls", namespace="structure")),
]

urlpatterns += [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

lms/apps/account/urls.py
from django.urls import path

from .views import (
    CustomLoginView, users_list, users_add,
    user_detail, user_update, user_delete
)

app_name = 'account'

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('users/list/', users_list, name='users_list'),
    path('users/add/', users_add, name='add_user'),
    path('users/detail/<int:id>/', user_detail, name='user_detail'),
    path('users/update/<int:id>/', user_update, name='user_update'),
    path('users/delete/<int:id>/', user_delete, name='user_delete'),
]

lms/apps/structure/urls.py
from django.urls import path

from .views import *

app_name = 'structure'

urlpatterns = [
    path('academic-year/', academic_year_list, name='academic_year_list'),
    path('academic-year/create/', academic_year_create, name='academic_year_create'),
    path('academic-year/<int:pk>/delete/', academic_year_delete, name='academic_year_delete'),
    path('academic-year/<int:id>/detail/', academic_year_detail, name='academic_year_detail'),
    path('academic-year/<int:id>/update/', academic_year_update, name='academic_year_update'),
    
    path('kafedra/', kafedra_list, name='kafedra_list'),
    path('kafedra/create/', kafedra_create, name='kafedra_create'),
    path('kafedra/<int:pk>/delete/', kafedra_delete, name='kafedra_delete'),
    path('kafedra/<int:id>/detail/', kafedra_detail, name='kafedra_detail'),
    path('kafedra/<int:id>/update/', kafedra_update, name='kafedra_update'),
    
    path('lesson-time/', lesson_time_list, name='lesson_time_list'),
    path('lesson-time/create/', lesson_time_create, name='lesson_time_create'),
    path('lesson-time/<int:pk>/delete/', lesson_time_delete, name='lesson_time_delete'),
    path('lesson-time/<int:id>/detail/', lesson_time_detail, name='lesson_time_detail'),
    path('lesson-time/<int:id>/update/', lesson_time_update, name='lesson_time_update'),
    
    path('science/', science_list, name='science_list'),
    path('science/create/', science_create, name='science_create'),
    path('science/<int:pk>/delete/', science_delete, name='science_delete'),
    path('science/<int:id>/detail/', science_detail, name='science_detail'),
    path('science/<int:id>/update/', science_update, name='science_update'),
    
    path('student-group/', student_group_list, name='student_group_list'),
    path('student-group/create/', student_group_create, name='student_group_create'),
    path('student-group/<int:pk>/delete/', student_group_delete, name='student_group_delete'),
    path('student-group/<int:id>/detail/', student_group_detail, name='student_group_detail'),
    path('student-group/<int:id>/update/', student_group_update, name='student_group_update'),
    path('student-group/<int:pk>/reject/user/<int:user_id>/', student_group_reject_student, name='student_group_reject_student'),
    
    path('science-group/', science_group_list, name='science_group_list'),
    path('science-group/create/', science_group_create, name='science_group_create'),
    path('science-group/<int:pk>/delete/', science_group_delete, name='science_group_delete'),
    path('science-group/<int:id>/detail/', science_group_detail, name='science_group_detail'),
    path('science-group/<int:id>/update/', science_group_update, name='science_group_update'),
]

lms/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("lms.apps.account.urls", namespace="account")),
    path("main/", include("lms.apps.main.urls", namespace="main")),
    path("structure/", include("lms.apps.structure.urls", namespace="structure")),
]

urlpatterns += [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

lms/apps/structure/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import Http404

from .models import *
from .forms import *


def academic_year_list(request):
    academic_years = AcademicYear.objects.all()
    context = {
        'academic_years': academic_years
    }
    return render(request, 'structure/academic-year.html', context)

def academic_year_delete(request, pk):
    if request.method == 'POST':
        academic_year = AcademicYear.objects.get(id=pk)
        academic_year.delete()
        return redirect('structure:academic_year_list')
    else:
        return Http404()

def academic_year_detail(request, id):
    academic_year = AcademicYear.objects.get(pk=id)
    context = {
        'academic_year': academic_year
    }
    return render(request, 'structure/academ-detail.html', context)

def academic_year_update(request, id):
    academic_year = AcademicYear.objects.get(pk=id)
    if request.method == 'POST':
        form = AcademicYearForm(request.POST, instance=academic_year)
        if form.is_valid():
            form.save()
            return redirect('structure:academic_year_list')
    else:
        form = AcademicYearForm(instance=academic_year)
    return render(request, 'structure/academ-update.html', {'form': form})

def academic_year_create(request):
    if request.method == 'POST':
        form = AcademicYearForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('structure:academic_year_list')
    else:
        form = AcademicYearForm()
    return render(request, 'structure/academ-update.html', {'form': form})



def kafedra_list(request):
    kafedras = Kafedra.objects.all()
    context = {
        'kafedras': kafedras
    }
    return render(request, 'structure/kafedra.html', context)

def kafedra_delete(request, pk):
    if request.method == 'POST':
        kafedra = Kafedra.objects.get(id=pk)
        kafedra.delete()
        return redirect('structure:kafedra_list')
    else:
        return Http404()

def kafedra_detail(request, id):
    kafedra = Kafedra.objects.get(pk=id)
    context = {
        'kafedra': kafedra
    }
    return render(request, 'structure/kafedra-detail.html', context)

def kafedra_update(request, id):
    kafedra = Kafedra.objects.get(pk=id)
    if request.method == 'POST':
        form = KafedraForm(request.POST, instance=kafedra, request=request)
        if form.is_valid():
            form.save()
            return redirect('structure:kafedra_list')
    else:
        form = KafedraForm(instance=kafedra, request=request)
    return render(request, 'structure/kafedra-update.html', {'form': form})

def kafedra_create(request):
    if request.method == 'POST':
        form = KafedraForm(request.POST, request=request)
        if form.is_valid():
            kafedra = form.save(commit=False)
            kafedra.school = request.user.school
            kafedra.save()
            return redirect('structure:kafedra_list')
    else:
        form = KafedraForm(request=request)
    return render(request, 'structure/kafedra-update.html', {'form': form})



def lesson_time_list(request):
    lesson_times = LessonTime.objects.all()
    context = {
        'lesson_times': lesson_times
    }
    return render(request, 'structure/lesson-time.html', context)

def lesson_time_delete(request, pk):
    if request.method == 'POST':
        lesson_time = LessonTime.objects.get(id=pk)
        lesson_time.delete()
        return redirect('structure:lesson_time_list')
    else:
        return Http404()

def lesson_time_detail(request, id):
    lesson_time = LessonTime.objects.get(pk=id)
    context = {
        'lesson_time': lesson_time
    }
    return render(request, 'structure/lesson-time-detail.html', context)

def lesson_time_update(request, id):
    lesson_time = LessonTime.objects.get(pk=id)
    if request.method == 'POST':
        form = LessonTimeForm(request.POST, instance=lesson_time, request=request)
        if form.is_valid():
            form.save()
            return redirect('structure:lesson_time_list')
    else:
        form = LessonTimeForm(instance=lesson_time)
    return render(request, 'structure/lesson-time-update.html', {'form': form})

def lesson_time_create(request):
    if request.method == 'POST':
        form = LessonTimeForm(request.POST)
        if form.is_valid():
            lesson_time = form.save(commit=False)
            lesson_time.school = request.user.school
            lesson_time.save()
            return redirect('structure:lesson_time_list')
    else:
        form = LessonTimeForm()
    return render(request, 'structure/lesson-time-update.html', {'form': form})




def science_list(request):
    sciences = Science.objects.all()
    context = {
        'sciences': sciences
    }
    return render(request, 'structure/science.html', context)

def science_delete(request, pk):
    if request.method == 'POST':
        science = Science.objects.get(id=pk)
        science.delete()
        return redirect('structure:science_list')
    else:
        return Http404()

def science_detail(request, id):
    science = Science.objects.get(pk=id)
    context = {
        'science': science
    }
    return render(request, 'structure/science-detail.html', context)

def science_update(request, id):
    science = Science.objects.get(pk=id)
    if request.method == 'POST':
        form = ScienceForm(request.POST, instance=science, request=request)
        if form.is_valid():
            form.save()
            return redirect('structure:science_list')
    else:
        form = ScienceForm(instance=science)
    return render(request, 'structure/science-update.html', {'form': form})

def science_create(request):
    if request.method == 'POST':
        form = ScienceForm(request.POST)
        if form.is_valid():
            science = form.save(commit=False)
            science.school = request.user.school
            science.save()
            return redirect('structure:science_list')
    else:
        form = ScienceForm()
    return render(request, 'structure/science-update.html', {'form': form})




def student_group_list(request):
    student_groups = StudentGroup.objects.all()
    context = {
        'student_groups': student_groups
    }
    return render(request, 'structure/student-group.html', context)

def student_group_delete(request, pk):
    if request.method == 'POST':
        student_group = StudentGroup.objects.get(id=pk)
        student_group.delete()
        return redirect('structure:student_group_list')
    else:
        return Http404()

def student_group_detail(request, id):
    student_group = StudentGroup.objects.get(pk=id)
    context = {
        'student_group': student_group
    }
    return render(request, 'structure/student-group-detail.html', context)

def student_group_update(request, id):
    student_group = StudentGroup.objects.get(pk=id)
    if request.method == 'POST':
        form = StudentGroupForm(request.POST, instance=student_group, request=request)
        if form.is_valid():
            form.save()
            return redirect('structure:student_group_list')
    else:
        form = StudentGroupForm(instance=student_group, request=request)
    return render(request, 'structure/student-group-update.html', {'form': form})

def student_group_create(request):
    if request.method == 'POST':
        form = StudentGroupForm(request.POST, request=request)
        if form.is_valid():
            student_group = form.save(commit=False)
            student_group.school = request.user.school
            student_group.save()
            return redirect('structure:student-group_list')
    else:
        form = StudentGroupForm(request=request)
    return render(request, 'structure/student-group-update.html', {'form': form})


def student_group_reject_student(request, pk, user_id):
    if request.method == 'POST':
        student_group = StudentGroup.objects.get(id=pk)
        student = CustomUser.objects.get(id=user_id)
        student_group.students.remove(student)
        return redirect(reverse('structure:student_group_detail', args=[pk]))
    else:
        return Http404()
    
    
    
def science_group_list(request):
    science_groups = ScienceGroup.objects.all()
    context = {
        'science_groups': science_groups
    }
    return render(request, 'structure/science-group.html', context)

def science_group_delete(request, pk):
    if request.method == 'POST':
        science_group = ScienceGroup.objects.get(id=pk)
        science_group.delete()
        return redirect('structure:science_group_list')
    else:
        return Http404()

def science_group_detail(request, id):
    science_group = ScienceGroup.objects.get(pk=id)
    context = {
        'science_group': science_group
    }
    return render(request, 'structure/science-group-detail.html', context)

def science_group_update(request, id):
    science_group = ScienceGroup.objects.get(pk=id)
    if request.method == 'POST':
        form = ScienceGroupForm(request.POST, instance=science_group, request=request)
        if form.is_valid():
            form.save()
            return redirect('structure:science_group_list')
    else:
        form = ScienceGroupForm(instance=science_group, request=request)
    return render(request, 'structure/science-group-update.html', {'form': form})

def science_group_create(request):
    if request.method == 'POST':
        form = ScienceGroupForm(request.POST, request=request)
        if form.is_valid():
            science_group = form.save(commit=False)
            science_group.school = request.user.school
            science_group.save()
            return redirect('structure:science-group_list')
    else:
        form = ScienceGroupForm(request=request)
    return render(request, 'structure/science-group-update.html', {'form': form})

templates/structure/academ-detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}User Profile{% endblock %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'assets/css/user-grid.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/upload-image.css' %}">
{% endblock %}

{% block content%}
    <div class="dashboard-main-body">
      <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-24">
        <h6 class="fw-semibold mb-0">View Academic Year</h6>
        <ul class="d-flex align-items-center gap-2">
          <li class="fw-medium">
            <a href="index.html" class="d-flex align-items-center gap-1 hover-text-primary">
              <iconify-icon icon="solar:home-smile-angle-outline" class="icon text-lg"></iconify-icon>
              Dashboard
            </a>
          </li>
          <li>-</li>
          <li class="fw-medium">View Academic Year</li>
        </ul>
      </div>

      <div class="row gy-4">
        <div class="col-lg-8">
          <div class="user-grid-card position-relative border radius-16 overflow-hidden bg-base h-100">
            <div class="pb-24 ms-16 mb-24 me-16  mt--100">
              <div class="text-center border border-top-0 border-start-0 border-end-0">
               <h6 class="mb-0 mt-16">{{ user.get_full_name }}</h6>
                <span class="text-secondary-light mb-16">{{ user.email }}</span>
              </div>
              <div class="mt-24">
                <h6 class="text-xl mb-16">Academic year Info</h6>
                <ul>
                  <li class="d-flex align-items-center gap-1 mb-12">
                    <span class="w-30 text-md fw-semibold text-primary-light">Name</span>
                    <span class="w-70 text-secondary-light fw-medium">: {{ academic_year.name }}</span>
                  </li>
                  <li class="d-flex align-items-center gap-1 mb-12">
                    <span class="w-30 text-md fw-semibold text-primary-light"> Season</span>
                    <span class="w-70 text-secondary-light fw-medium">: {{ academic_year.season }}</span>
                  </li>
                  <li class="d-flex align-items-center gap-1 mb-12">
                    <span class="w-30 text-md fw-semibold text-primary-light"> Start Date</span>
                    <span class="w-70 text-secondary-light fw-medium">: {{ academic_year.start_date }}</span>
                  </li>
                  <li class="d-flex align-items-center gap-1 mb-12">
                    <span class="w-30 text-md fw-semibold text-primary-light"> End date</span>
                    <span class="w-70 text-secondary-light fw-medium">: {{ academic_year.end_date }}</span>
                  </li>
                  <li class="d-flex align-items-center gap-1 mb-12">
                    <span class="w-30 text-md fw-semibold text-primary-light"> Parent</span>
                    <span class="w-70 text-secondary-light fw-medium">: {{ academic_year.parent }}</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block my_scripts %}
  <script>
    // ======================== Upload Image Start =====================
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $('#imagePreview').css('background-image', 'url(' + e.target.result + ')');
          $('#imagePreview').hide();
          $('#imagePreview').fadeIn(650);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }
    $("#imageUpload").change(function () {
      readURL(this);
    });
    // ======================== Upload Image End =====================

    // ================== Password Show Hide Js Start ==========
    function initializePasswordToggle(toggleSelector) {
      $(toggleSelector).on('click', function () {
        $(this).toggleClass("ri-eye-off-line");
        var input = $($(this).attr("data-toggle"));
        if (input.attr("type") === "password") {
          input.attr("type", "text");
        } else {
          input.attr("type", "password");
        }
      });
    }
    // Call the function
    initializePasswordToggle('.toggle-password');
    // ========================= Password Show Hide Js End ===========================
  </script>
{% endblock %}

templates/structure/academic-year.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="dashboard-main-body">

      <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-24">
        <h6 class="fw-semibold mb-0">Basic Table</h6>
        <ul class="d-flex align-items-center gap-2">
          <li class="fw-medium">
            <a href="index.html" class="d-flex align-items-center gap-1 hover-text-primary">
              <iconify-icon icon="solar:home-smile-angle-outline" class="icon text-lg"></iconify-icon>
              Dashboard
            </a>
          </li>
          <li>-</li>
          <li class="fw-medium">Basic Table</li>
        </ul>
      </div>

      <div class="card basic-data-table">
        <div class="card-header border-bottom bg-base py-16 px-24 d-flex align-items-center flex-wrap gap-3 justify-content-between">
            <div class="d-flex align-items-center flex-wrap gap-3">
              <span class="text-md fw-medium text-secondary-light mb-0">Show</span>
              <select class="form-select form-select-sm w-auto ps-12 py-6 radius-12 h-40-px">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
              </select>
              <form class="navbar-search">
                <input type="text" class="bg-base h-40-px w-auto" name="search" placeholder="Search" />
                <iconify-icon icon="ion:search-outline" class="icon"></iconify-icon>
              </form>
              <select class="form-select form-select-sm w-auto ps-12 py-6 radius-12 h-40-px">
                <option>Status</option>
                <option>Active</option>
                <option>Inactive</option>
              </select>
            </div>
            <a href="{% url 'structure:academic_year_create' %}" class="btn btn-primary text-sm btn-sm px-12 py-12 radius-8 d-flex align-items-center gap-2"><iconify-icon icon="ic:baseline-plus" class="icon text-xl line-height-1"></iconify-icon>Add new Academic year</a>
        </div>
        <div class="card-body">
          <table class="table bordered-table mb-0" data-page-length='10'>
            <thead>
              <tr>
                <th scope="col">
                  <div class="form-check style-check d-flex align-items-center">
                    <input class="form-check-input" type="checkbox">
                    <label class="form-check-label">
                      №
                    </label>
                  </div>
                </th>
                <th scope="col">Name</th>
                <th scope="col">Season</th>
                <th scope="col">Start Date</th>
                <th scope="col">End Date</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for academic_year in academic_years %}
              <tr>
                <td>
                  <div class="form-check style-check d-flex align-items-center">
                    <input class="form-check-input" type="checkbox">
                    <label class="form-check-label">
                      {{ forloop.counter }}
                    </label>
                  </div>
                </td>
                <td><a href="javascript:void(0)" class="text-primary-600">{{ academic_year.name }}</a></td>
                <td>
                  <div class="d-flex align-items-center">
                    <img src="assets/images/user-list/user-list1.png" alt="" class="flex-shrink-0 me-12 radius-8">
                    <h6 class="text-md mb-0 fw-medium flex-grow-1">{{ academic_year.season}}</h6>
                  </div>
                </td>
                <td>{{ academic_year.start_date }}</td>
                <td>{{ academic_year.end_date }}</td>
                <td>
                  {% if academic_year.is_active %}
                    <span class="bg-success-focus text-success-main px-24 py-4 rounded-pill fw-medium text-sm">Active</span>
                  {% else %}
                    <span class="bg-warning-focus text-warning-main px-24 py-4 rounded-pill fw-medium text-sm">Not active</span>
                  {% endif %}
                </td>
                <td>
                  <a href="{% url 'structure:academic_year_detail' academic_year.id %}"
                    class="w-32-px h-32-px bg-primary-light text-primary-600 rounded-circle d-inline-flex align-items-center justify-content-center">
                    <iconify-icon icon="iconamoon:eye-light"></iconify-icon>
                  </a>
                  <a href="{% url 'structure:academic_year_update' academic_year.id %}"
                    class="w-32-px h-32-px bg-success-focus text-success-main rounded-circle d-inline-flex align-items-center justify-content-center">
                    <iconify-icon icon="lucide:edit"></iconify-icon>
                  </a>
                  <form action="{% url 'structure:academic_year_delete' academic_year.id %}" method='post'>
                    {% csrf_token %}
                    <button type="submit"
                      class="w-32-px h-32-px bg-danger-focus text-danger-main rounded-circle d-inline-flex align-items-center justify-content-center">
                      <iconify-icon icon="mingcute:delete-2-line"></iconify-icon>
                    </button>
                  </form>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
{% endblock %}

{% block my_scripts %}
  <script>
    let table = new DataTable('#dataTable');
  </script>
{% endblock %}

templates/structure/kafedra.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="dashboard-main-body">

      <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-24">
        <h6 class="fw-semibold mb-0">Basic Table</h6>
        <ul class="d-flex align-items-center gap-2">
          <li class="fw-medium">
            <a href="index.html" class="d-flex align-items-center gap-1 hover-text-primary">
              <iconify-icon icon="solar:home-smile-angle-outline" class="icon text-lg"></iconify-icon>
              Dashboard
            </a>
          </li>
          <li>-</li>
          <li class="fw-medium">Basic Table</li>
        </ul>
      </div>

      <div class="card basic-data-table">
        <div class="card-header border-bottom bg-base py-16 px-24 d-flex align-items-center flex-wrap gap-3 justify-content-between">
            <div class="d-flex align-items-center flex-wrap gap-3">
              <span class="text-md fw-medium text-secondary-light mb-0">Show</span>
              <select class="form-select form-select-sm w-auto ps-12 py-6 radius-12 h-40-px">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
                <option>6</option>
                <option>7</option>
                <option>8</option>
                <option>9</option>
                <option>10</option>
              </select>
              <form class="navbar-search">
                <input type="text" class="bg-base h-40-px w-auto" name="search" placeholder="Search" />
                <iconify-icon icon="ion:search-outline" class="icon"></iconify-icon>
              </form>
              <select class="form-select form-select-sm w-auto ps-12 py-6 radius-12 h-40-px">
                <option>Status</option>
                <option>Active</option>
                <option>Inactive</option>
              </select>
            </div>
            <a href="{% url 'structure:kafedra_create' %}" class="btn btn-primary text-sm btn-sm px-12 py-12 radius-8 d-flex align-items-center gap-2"><iconify-icon icon="ic:baseline-plus" class="icon text-xl line-height-1"></iconify-icon>Add New Kafedra</a>
        </div>
        <div class="card-body">
          <table class="table bordered-table mb-0" data-page-length='10'>
            <thead>
              <tr>
                <th scope="col">
                  <div class="form-check style-check d-flex align-items-center">
                    <input class="form-check-input" type="checkbox">
                    <label class="form-check-label">
                      №
                    </label>
                  </div>
                </th>
                <th scope="col">Name</th>
                <th scope="col">Code</th>
                <th scope="col">Department user</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for kafedra in kafedras %}
              <tr>
                <td>
                  <div class="form-check style-check d-flex align-items-center">
                    <input class="form-check-input" type="checkbox">
                    <label class="form-check-label">
                      {{ forloop.counter }}
                    </label>
                  </div>
                </td>
                <td><a href="javascript:void(0)" class="text-primary-600">{{ kafedra.name }}</a></td>
                <td>
                  <div class="d-flex align-items-center">
                    <img src="assets/images/user-list/user-list1.png" alt="" class="flex-shrink-0 me-12 radius-8">
                    <h6 class="text-md mb-0 fw-medium flex-grow-1">{{ kafedra.code}}</h6>
                  </div>
                </td>
                <td>{{ kafedra.department_user }}</td>
                <td>
                  {% if kafedra.is_active %}
                    <span class="bg-success-focus text-success-main px-24 py-4 rounded-pill fw-medium text-sm">Active</span>
                  {% else %}
                    <span class="bg-warning-focus text-warning-main px-24 py-4 rounded-pill fw-medium text-sm">Not active</span>
                  {% endif %}
                </td>
                <td>
                  <a href="{% url 'structure:kafedra_detail' kafedra.id %}"
                    class="w-32-px h-32-px bg-primary-light text-primary-600 rounded-circle d-inline-flex align-items-center justify-content-center">
                    <iconify-icon icon="iconamoon:eye-light"></iconify-icon>
                  </a>
                  <a href="{% url 'structure:kafedra_update' kafedra.id %}"
                    class="w-32-px h-32-px bg-success-focus text-success-main rounded-circle d-inline-flex align-items-center justify-content-center">
                    <iconify-icon icon="lucide:edit"></iconify-icon>
                  </a>
                   <form action="{% url 'structure:kafedra_delete' kafedra.id %}" method="post" >
                     {% csrf_token %}
                      <button type="submit"
                      class="w-32-px h-32-px bg-danger-focus text-danger-main rounded-circle d-inline-flex align-items-center justify-content-center">
                      <iconify-icon icon="mingcute:delete-2-line"></iconify-icon>
                      </button>
                   </form>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
{% endblock %}

{% block my_scripts %}
  <script>
    let table = new DataTable('#dataTable');
  </script>
{% endblock %}