config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("account.urls", namespace="account")),
    path("main/", include("main.urls", namespace="main")),
    path("structure/", include("structure.urls", namespace="structure")),
]

urlpatterns += [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

lms/apps/main/urls.py
from django.urls import path

from .views import *

app_name = 'main'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('director/', director_dashboard, name='director_dashboard'),
    
    path('school/detail/', school_detail, name='school_detail'),
    
    path('teacher/', teacher_dashboard, name='teacher_dashboard'),
    path('teacher/groups/', teacher_group, name='teacher_group'),
    path('teacher/groups/detail<int:id>/', teacher_group_detail, name='teacher_group_detail'),
    
    path('module/create/<int:group_id>/', teacher_module_create, name='teacher_module_create'),
    
    path('lesson/detail/<int:id>/', lesson_detail, name="lesson_detail"),
    path('lesson/create/<int:module_id>/', teacher_lesson_create, name='teacher_lesson_create'),
    path('lesson/update/<int:lesson_id>/', teacher_lesson_update, name='teacher_lesson_update'),
    
    path('nb/create/<int:lesson_id>/', nb_create, name='nb_create'),
]

lms/apps/structure/urls.py
from django.urls import path

from .views import *

app_name = 'structure'

urlpatterns = [
    path('academic-year/', academic_year_list, name='academic_year_list'),
    path('academic-year/create/', academic_year_create, name='academic_year_create'),
    path('academic-year/<int:pk>/delete/', academic_year_delete, name='academic_year_delete'),
    path('academic-year/<int:id>/detail/', academic_year_detail, name='academic_year_detail'),
    path('academic-year/<int:id>/update/', academic_year_update, name='academic_year_update'),
    
    path('kafedra/', kafedra_list, name='kafedra_list'),
    path('kafedra/create/', kafedra_create, name='kafedra_create'),
    path('kafedra/<int:pk>/delete/', kafedra_delete, name='kafedra_delete'),
    path('kafedra/<int:id>/detail/', kafedra_detail, name='kafedra_detail'),
    path('kafedra/<int:id>/update/', kafedra_update, name='kafedra_update'),
    
    path('lesson-time/', lesson_time_list, name='lesson_time_list'),
    path('lesson-time/create/', lesson_time_create, name='lesson_time_create'),
    path('lesson-time/<int:pk>/delete/', lesson_time_delete, name='lesson_time_delete'),
    path('lesson-time/<int:id>/detail/', lesson_time_detail, name='lesson_time_detail'),
    path('lesson-time/<int:id>/update/', lesson_time_update, name='lesson_time_update'),
    
    path('science/', science_list, name='science_list'),
    path('science/create/', science_create, name='science_create'),
    path('science/<int:pk>/delete/', science_delete, name='science_delete'),
    path('science/<int:id>/detail/', science_detail, name='science_detail'),
    path('science/<int:id>/update/', science_update, name='science_update'),
    
    path('student-group/', student_group_list, name='student_group_list'),
    path('student-group/create/', student_group_create, name='student_group_create'),
    path('student-group/<int:pk>/delete/', student_group_delete, name='student_group_delete'),
    path('student-group/<int:id>/detail/', student_group_detail, name='student_group_detail'),
    path('student-group/<int:id>/update/', student_group_update, name='student_group_update'),
    path('student-group/<int:pk>/reject/user/<int:user_id>/', student_group_reject_student, name='student_group_reject_student'),
    
    path('science-group/', science_group_list, name='science_group_list'),
    path('science-group/create/', science_group_create, name='science_group_create'),
    path('science-group/<int:pk>/delete/', science_group_delete, name='science_group_delete'),
    path('science-group/<int:id>/detail/', science_group_detail, name='science_group_detail'),
    path('science-group/<int:id>/update/', science_group_update, name='science_group_update'),
]

lms/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("lms.apps.account.urls", namespace="account")),
    path("main/", include("lms.apps.main.urls", namespace="main")),
    path("structure/", include("lms.apps.structure.urls", namespace="structure")),
]

urlpatterns += [
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

apps/main/models.py
from django.db import models
from account.models import CustomUser
from structure.models import ROOM_GROUP_TYPE, LANGUAGES, StudentGroup, ScienceGroup
from mptt.models import MPTTModel, TreeForeignKey
from ckeditor.fields import RichTextField


class School(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255, null=True, blank=True)
    logo = models.ImageField(upload_to='school/logo/', blank=True, null=True)
    about = models.TextField(null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ['name']
        
    def __str__(self):
        return f"{self.name}"


LESSON_STATUS_CHOICES = (
    ('otildi', 'Otildi'),
    ('otilmadi', 'Otilmadi'),
    ('qoldirildi', 'Qoldirildi'),
)


class Task(models.Model):
    group = models.ForeignKey(ScienceGroup, on_delete=models.SET_NULL, null=True, blank=True,
                              related_name='task_to_group')
    lesson = models.ForeignKey('Lesson', on_delete=models.SET_NULL, null=True, blank=True,
                              related_name='task_to_lesson')
    title = models.CharField(max_length=225)
    source = models.FileField(upload_to='task_source/')
    deadline = models.DateTimeField(null=True, blank=True)
    grade = models.DecimalField(max_digits=10, decimal_places=2)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.title


class Submission(models.Model):
    task = models.ForeignKey(Task, on_delete=models.SET_NULL, null=True, related_name='submission_to_task')
    student = models.ForeignKey('account.CustomUser', on_delete=models.SET_NULL, null=True,
                                related_name='submissions_to_student')
    source = models.FileField(upload_to='submissions/', null=True, blank=True)
    grade = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return f"Submission #{self.id}"


class Module(models.Model):
    group = models.ForeignKey(ScienceGroup,
                               related_name='modules',
                               on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f'{self.order}. {self.title}'


class Lesson(models.Model):
    name = models.CharField(max_length=255)
    lesson_date = models.DateField(null=True, blank=True)
    status = models.CharField(choices=LESSON_STATUS_CHOICES, null=True, blank=True, max_length=223)
    module = models.ForeignKey(Module, on_delete=models.SET_NULL, null=True,related_name='lesson_to_group_model')
    about = models.CharField(max_length=255, blank=True, null=True)
    text = RichTextField(config_name='default')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name


class DailyRatings(models.Model):
    science_group = models.ForeignKey(ScienceGroup,
                               related_name='daily_taings',
                               on_delete=models.CASCADE)
    student = models.ForeignKey('account.CustomUser', on_delete=models.SET_NULL, null=True,
                                related_name='dailyrating_to_student')
    ball = models.DecimalField(max_digits=10,
                               decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.science_group} > {self.student}'


class NBandRating(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='nb_and_rating_to_lesson')
    is_checked = models.BooleanField(default=False)
    is_rated = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class LessonSource(models.Model):
    teacher = models.ForeignKey('account.CustomUser', on_delete=models.SET_NULL, null=True,
                                related_name='lessonsource_to_teacher')
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, null=True, blank=True,
                               related_name='lessonsource_to_lesson')
    file = models.FileField(upload_to='lesson_sources/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    def __str__(self):
        return f"LessonSource #{self.id}"


class NB(models.Model):
    student = models.ForeignKey('account.CustomUser', on_delete=models.SET_NULL, null=True, related_name='nb_to_student')
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, null=True, related_name='nb_to_lesson')
    cause_status = models.BooleanField(null=True, blank=True)
    type_cause = models.CharField(max_length=255, null=True, blank=True)
    cause_file = models.FileField(upload_to='cause_file/', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    def __str__(self):
        return f"NB #{self.id} - {self.student}"


class RatingNotebook(models.Model):
    student = models.ForeignKey('account.CustomUser', on_delete=models.SET_NULL, null=True,
                                related_name='ratingnotebook_to_student')
    science_name = models.ForeignKey('structure.Science', on_delete=models.SET_NULL, null=True, blank=True,
                                     related_name="individual_plans", limit_choices_to={'level': 1})
    semester = models.ForeignKey('structure.AcademicYear', on_delete=models.SET_NULL, null=True,
                                 related_name='ratingnotebook_to_semester')
    grade = models.DecimalField(max_digits=10, decimal_places=2)  # 2,..5
    ball = models.DecimalField(max_digits=10,
                               decimal_places=2)
    comment = models.CharField(max_length=255, null=True,
                               blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return f"RatingNotebook #{self.id}"

apps/main/forms.py
from django import forms

from ckeditor.widgets import CKEditorWidget

from account.models import RoleName
from .models import School, Module, Lesson, NB


class SchoolForm(forms.ModelForm):
    class Meta:
        model = School
        exclude = ['created_at', 'updated_at',]
        widgets = {
            'address': forms.TextInput(attrs={'placeholder': 'Enter school address'}),
            'phone': forms.TextInput(attrs={'placeholder': 'Enter phone number'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Enter email address'}),
        }


class ModuleForm(forms.ModelForm):
    class Meta:
        model = Module
        fields = ['title', 'description', 'order',]


class LessonForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Lesson
        fields = ['name', 'lesson_date', 'about', 'text', 'is_active']


class NBForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.lesson = kwargs.pop('lesson')
        super().__init__(*args, **kwargs)
        
        students = self.lesson.module.group.group.students.filter(
            role__name=RoleName.STUDENT
        ).order_by('last_name', 'first_name')
        
        for student in students:
            self.fields[f'student_{student.id}'] = forms.BooleanField(
                required=False,
                label=f"{student.last_name} {student.first_name}",
                initial=True
            )

lms/apps/main/forms.py
from django import forms

from ckeditor.widgets import CKEditorWidget

from lms.apps.account.models import RoleName
from .models import School, Module, Lesson, NB


class SchoolForm(forms.ModelForm):
    class Meta:
        model = School
        exclude = ['created_at', 'updated_at',]
        widgets = {
            'address': forms.TextInput(attrs={'placeholder': 'Enter school address'}),
            'phone': forms.TextInput(attrs={'placeholder': 'Enter phone number'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Enter email address'}),
        }


class ModuleForm(forms.ModelForm):
    class Meta:
        model = Module
        fields = ['title', 'description', 'order',]


class LessonForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Lesson
        fields = ['name', 'lesson_date', 'about', 'text', 'is_active']


class NBForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.lesson = kwargs.pop('lesson')
        super().__init__(*args, **kwargs)
        
        students = self.lesson.module.group.group.students.filter(
            role__name=RoleName.STUDENT
        ).order_by('last_name', 'first_name')
        
        for student in students:
            self.fields[f'student_{student.id}'] = forms.BooleanField(
                required=False,
                label=f"{student.last_name} {student.first_name}",
                initial=True
            )

templates/main/lesson-detail.html
{% extends 'base_teacher.html' %}
{% load static %}

{% block title %}User Profile{% endblock %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'assets/css/user-grid.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/upload-image.css' %}">
{% endblock %}

{% block content%}
    <div class="dashboard-main-body">
      <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-24">
        <h6 class="fw-semibold mb-0">View Lesson</h6>
        <ul class="d-flex align-items-center gap-2">
          <li class="fw-medium">
            <a href="index.html" class="d-flex align-items-center gap-1 hover-text-primary">
              <iconify-icon icon="solar:home-smile-angle-outline" class="icon text-lg"></iconify-icon>
              Dashboard
            </a>
          </li>
          <li>-</li>
          <li class="fw-medium">View Lesson</li>
        </ul>
      </div>

      <div class="card basic-data-table">
        <div class="card-header border-bottom bg-base py-16 px-24 d-flex align-items-center flex-wrap gap-3 justify-content-between">
            <div class="d-flex align-items-center flex-wrap gap-3">
              <span class="text-md fw-medium text-secondary-light mb-0">{{ lesson.name }}</span>
            </div>
            <div class="d-flex">
              {% if checked == False %}<a href="{% url 'main:nb_create' lesson.id %}" class="btn btn-primary text-sm btn-sm px-12 py-12 radius-8 d-flex align-items-center gap-2"><iconify-icon icon="ic:baseline-plus" class="icon text-xl line-height-1"></iconify-icon>Yo'qlama</a>{% endif %}
              <a href="{% url 'main:teacher_lesson_update' lesson.id %}" class="btn btn-primary text-sm btn-sm px-12 py-12 radius-8 d-flex align-items-center gap-2"><iconify-icon icon="ic:baseline-plus" class="icon text-xl line-height-1"></iconify-icon>Update Lesson</a>
            </div>
        </div>
        <div class="card-body">
          {{ lesson.text|safe }}
        </div>
      </div>
    </div>
{% endblock %}

templates/main/lesson-update.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}User Profile{% endblock %}

{% block styles %}
  <link rel="stylesheet" href="{% static 'assets/css/user-grid.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/upload-image.css' %}">
  <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
  <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

{% block content%}
    <div class="dashboard-main-body">
      <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-24">
        <h6 class="fw-semibold mb-0">View Lesson</h6>
        <ul class="d-flex align-items-center gap-2">
          <li class="fw-medium">
            <a href="index.html" class="d-flex align-items-center gap-1 hover-text-primary">
              <iconify-icon icon="solar:home-smile-angle-outline" class="icon text-lg"></iconify-icon>
              Dashboard
            </a>
          </li>
          <li>-</li>
          <li class="fw-medium">Lesson</li>
        </ul>
      </div>

      <div class="row gy-4">
        <div class="col-lg-12">
          <div class="card h-100">
            <div class="card-body p-24">
              <ul class="nav border-gradient-tab nav-pills mb-20 d-inline-flex" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                  <button class="nav-link d-flex align-items-center px-24 active" id="pills-edit-profile-tab"
                    data-bs-toggle="pill" data-bs-target="#pills-edit-profile" type="button" role="tab"
                    aria-controls="pills-edit-profile" aria-selected="true">
                    Edit Lesson
                  </button>
                </li>
              </ul>

              <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-edit-profile" role="tabpanel"
                  aria-labelledby="pills-edit-profile-tab" tabindex="0">
                  <h6 class="text-md text-primary-light mb-16">Lesson</h6>
                  <form method="post">
                    {% csrf_token %}
                    {{ form.media }}
                    <div class="row">
                      <div class="col-sm-6">
                        <div class="mb-20">
                          <label for="name" class="form-label fw-semibold text-primary-light text-sm mb-8">Name
                            <span class="text-danger-600">*</span></label>
                          {% render_field form.name type="text" class="form-control radius-8" placeholder="Name" %}
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="mb-20">
                          <label for="email" class="form-label fw-semibold text-primary-light text-sm mb-8">Lesson Date<span
                              class="text-danger-600">*</span></label>
                          {% render_field form.lesson_date type="date" class="form-control radius-8" %}
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="mb-20">
                          <label for="id_description" class="form-label fw-semibold text-primary-light text-sm mb-8">About
                            <span class="text-danger-600">*</span> </label>
                          {% render_field form.about class="form-control radius-8" %}
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="mb-20">
                          <label for="desig" class="form-label fw-semibold text-primary-light text-sm mb-8">Active
                            <span class="text-danger-600">*</span> </label>
                          {% render_field form.is_active class="form-control radius-8" %}
                        </div>
                      </div>
                      <div class="col-sm-12">
                        <div class="mb-20">
                          <label for="desig" class="form-label fw-semibold text-primary-light text-sm mb-8">Content
                            <span class="text-danger-600">*</span> </label>
                          {{ form.text }}
                        </div>
                      </div>
                      
                    </div>
                    <div class="d-flex align-items-center justify-content-center gap-3">
                      <a href="{% url 'structure:lesson_time_list' %}"
                        class="border border-danger-600 bg-hover-danger-200 text-danger-600 text-md px-56 py-11 radius-8">
                        Cancel
                      </a>
                      <button type="submit"
                        class="btn btn-primary border border-primary-600 text-md px-56 py-12 radius-8">
                        Save
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block my_scripts %}
  <script>
    // ======================== Upload Image Start =====================
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $('#imagePreview').css('background-image', 'url(' + e.target.result + ')');
          $('#imagePreview').hide();
          $('#imagePreview').fadeIn(650);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }
    $("#imageUpload").change(function () {
      readURL(this);
    });
    // ======================== Upload Image End =====================

    // ================== Password Show Hide Js Start ==========
    function initializePasswordToggle(toggleSelector) {
      $(toggleSelector).on('click', function () {
        $(this).toggleClass("ri-eye-off-line");
        var input = $($(this).attr("data-toggle"));
        if (input.attr("type") === "password") {
          input.attr("type", "text");
        } else {
          input.attr("type", "password");
        }
      });
    }
    // Call the function
    initializePasswordToggle('.toggle-password');
    // ========================= Password Show Hide Js End ===========================
  </script>
{% endblock %}

templates/main/module.html
{% extends 'base_teacher.html' %}

{% block content %}
  <div class="dashboard-main-body">
    <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-24">
      <h6 class="fw-semibold mb-0">Faq</h6>
      <ul class="d-flex align-items-center gap-2">
        <li class="fw-medium">
          <a href="index.html" class="d-flex align-items-center gap-1 hover-text-primary"><iconify-icon icon="solar:home-smile-angle-outline" class="icon text-lg"></iconify-icon>Dashboard</a>
        </li>
        <li>-</li>
        <li class="fw-medium">Faq</li>
      </ul>
    </div>

    <div class="card basic-data-table">
      <div class="card-header p-0 border-0">
        <div class="responsive-padding-40-150 bg-light-pink">
          <div class="row gy-4 align-items-center">
            <div class="col-xl-7">
              <h4 class="mb-20">Frequently asked questions.</h4>
              <p class="mb-0 text-secondary-light max-w-634-px text-xl">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard du text ever since the 1500s, when an unkn</p>
            </div>
            <div class="col-xl-5 d-xl-block d-none">
              <img src="assets/images/faq-img.png" alt="" />
            </div>
          </div>
        </div>
      </div>
      <div class="card-body bg-base responsive-padding-40-150">
        <div class="row gy-4">
          <div class="col-lg-4">
            <div class="active-text-tab nav flex-column nav-pills bg-base shadow py-0 px-24 radius-12 border" id="v-pills-tab" role="tablist" aria-orientation="vertical">
              <a href="{% url 'main:teacher_module_create' group.id %}" class="btn rounded-pill btn-success-100 text-success-600 radius-8 text-xl px-20 py-16  border-bottom" >Add new module</a>
              {% for module in group.modules.all %}
                <button class="nav-link text-secondary-light fw-semibold text-xl px-0 py-16 border-bottom" id="v-pills-{{module.id}}-tab" data-bs-toggle="pill" data-bs-target="#v-pills-{{module.id}}" type="button" role="tab" aria-controls="v-pills-{{module.id}}" aria-selected="false">{{ module.title }}</button>
              {% endfor %}
            </div>
          </div>
          <div class="col-lg-8">
            <div class="tab-content" id="v-pills-tabContent">
              {% for module in group.modules.all %}
                <div class="tab-pane fade" id="v-pills-{{module.id}}" role="tabpanel" aria-labelledby="v-pills-{{module.id}}-tab" tabindex="0">
                  <div class="accordion" id="accordionExampleThree">
                    <div class="accordion-item">
                      <a href="{% url 'main:teacher_lesson_create' module.id %}" class="accordion-header w-100 btn rounded-pill btn-success-100 text-success-600 radius-8 text-xl px-20 py-16  border-bottom" >Add new lesson</a>
                    </div>
                    {% for lesson in module.lesson_to_group_model.all %}
                    <div class="accordion-item">
                      <h2 class="accordion-header"><button class="accordion-button text-primary-light text-xl{% if forloop.count == 1 %}{% else %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#c-{{ lesson.id }}" aria-expanded="true" aria-controls="c-{{ lesson.id }}">{{ lesson.name }}</button></h2>
                      <div id="c-{{ lesson.id }}" class="accordion-collapse collapse {% if forloop.counter == 1 %}show{% endif %}" data-bs-parent="#accordionExampleThree">
                        <div class="accordion-body">{{ lesson.about }}</div>
                        <a href="{% url 'main:lesson_detail' lesson.id %}" class="accordion-header w-100 btn rounded-pill btn-success-100 text-success-600 radius-8 text-xl px-20 py-16  border-bottom" >Ko'rish</a>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block my_scripts %}
  <script>
    let table = new DataTable('#dataTable')
  </script>
{% endblock %}

templates/main/teacher-group.html
{% extends 'base_teacher.html' %}

{% block content %}
  <div class="dashboard-main-body">
    <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-24">
      <h6 class="fw-semibold mb-0">Teaching groups</h6>
      <ul class="d-flex align-items-center gap-2">
        <li class="fw-medium">
          <a href="index.html" class="d-flex align-items-center gap-1 hover-text-primary"><iconify-icon icon="solar:home-smile-angle-outline" class="icon text-lg"></iconify-icon>Dashboard</a>
        </li>
        <li>-</li>
        <li class="fw-medium">Teaching groups</li>
      </ul>
    </div>

    <div class="row gy-4">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header">
            <h5 class="card-title mb-0">Group info</h5>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table striped-table mb-0">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Science</th>
                    <th scope="col">Code</th>
                    <th scope="col">Students Count</th>
                    <th scope="col" class="text-center">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for group in groups %}
                    <tr>
                      <td>
                        <div class="d-flex align-items-center">
                          <img src="assets/images/product/product-img1.png" alt="" class="flex-shrink-0 me-12 radius-8 me-12" />
                          <div class="flex-grow-1">
                            <h6 class="text-md mb-0 fw-normal">{{ group.name }}</h6>
                            <span class="text-sm text-secondary-light fw-normal">{{ group.group.name }}</span>
                          </div>
                        </div>
                      </td>
                      <td>{{ group.science.name }}</td>
                      <td>{{ group.code}}</td>
                      <td>{{ group.group.students.count }}</td>
                      <td class="text-center">
                        <a href="{% url 'main:teacher_group_detail' group.id %}"
                          class="w-32-px h-32-px bg-primary-light text-primary-600 rounded-circle d-inline-flex align-items-center justify-content-center">
                          <iconify-icon icon="iconamoon:eye-light"></iconify-icon>
                        </a>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <!-- card end -->
      </div>
    </div>
  </div>
{% endblock %}